import type { Metadata } from 'next';
import './globals.css';
import { Yeon_Sung } from 'next/font/google';

const logoFont = Yeon_Sung({
  variable: '--logo-font',
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${logoFont.variable}`}>{children}</body>
    </html>
  );
}
