import type { Metadata } from 'next';
import './globals.css';
import { FontClassNames } from '@/assets/font/font';
import Navbar from '@/components/common/navbar/Navbar';
import CommonLayout from '@/components/common/CommonLayout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={FontClassNames}>
        <CommonLayout>{children}</CommonLayout>
      </body>
    </html>
  );
}
